### ISSUE TITLE
Sort imports based on first and third party

### ISSUE THREAD

**Issue by kiliankoe** [dasdom/SwiftTools#1]
As far as I can tell the new sort imports feature currently sorts imports alphabetically. Other similar formatters usually try and separate imports based on if they're first or third party, meaning something (contrived) like the following

```swift
import UIKit
import Bar
import Foundation
import Foo
```

would be sorted into this

```swift
import Foundation
import UIKit

import Bar
import Foo
```

This would probably mean having to maintain a list of first party modules or is that something that can maybe be read from the system?

**Comment by dasdom** [comment]
Should work now.
