### ISSUE TITLE
Repeated import sorting adds more blank lines

### ISSUE THREAD

**Issue by finestructure** [dasdom/SwiftTools#2]
I've just spotted a tiny cosmetic issue with import sorting: if you repeatedly sort it keeps adding another blank line after the imports each time.

**Comment by dasdom** [comment]
Could you please check if you have the current version? I thought I'd fixed that in the last version.

**Comment by finestructure** [comment]
Should be - I downloaded just before posting the issue. I’m not at my Mac right now but will report back the version once I am!

**Comment by finestructure** [comment]
I'm on version 1.0.1 (3) as per the Abount menu

**Comment by dasdom** [comment]
Thanks! This means the bug is still present. I'll fix it in the version after the next one.

**Comment by dasdom** [comment]
Is fixed now in the repo. Will take some time until it will come to the App Store.

**Comment by dasdom** [comment]
Waiting for review

**Comment by finestructure** [comment]
That's working now - thanks for the quick update!
